Breached threshold issue
awslabs/synchro-charts pull request #183
Opened 2022-11-15 19:43 UTC by jebek

## Overview
Addresses https://github.com/awslabs/synchro-charts/issues/153

Quip explaining the issue: https://quip-amazon.com/JjqtAIhIbwQw/Synchro-Charts-breachedThreshold-Multiple-Threshold-Issue

Basically, thresholds were originally designed to only consider a breach IF the data point is between 2 intersecting thresholds. This happens when there is a lower 'greater than' comparator and a higher 'less than' comparator.

![Screen Shot 2022-11-15 at 11 38 36 AM](https://user-images.githubusercontent.com/1039853/202010202-fa47622e-c8f6-4435-b61d-22668b539a5e.png)

The issue here is that a user could reasonably expect that the data points beyond this intersected area would trigger a breached threshold. Even though this use case was intentionally designed, it leads to a confusing user experience.

To address this issue, this PR:

1. Removes the logic to only consider a breached threshold within the intersected area.

2. Add an operator to the threshold label to make it more clear what the threshold is actually doing.

3. Updates documentation to reflect these updates.

## Tests
[Include a link to the passing GitHub action running the test suite here.]

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-11-16 17:01 UTC, diehbria requested changes
the logic for determining what the 'most important threshold that is breaching a given point', does it properly take into account severity?

If i had a more severe threshold with the condition "greater than 0" and a second threshold that is "greater than 100" if my value is 101, will it correctly return the more severe threshold"?

2022-11-17 23:08 UTC, jebek commented on packages/synchro-charts/src/components/charts/common/annotations/utils.ts
> +   * https://quip-amazon.com/JjqtAIhIbwQw/Synchro-Charts-breachedThreshold-Multiple-Threshold-Issue
done.

2022-11-18 00:03 UTC, jebek commented
@diehbria 

Severity should now be addressed. After we find the breached thresholds, we look for the highest severity among those breached thresholds: https://github.com/awslabs/synchro-charts/pull/183/files#diff-d4d358a6fe4cbd74e77b0128e58965a48b750e6619f4f3b15f6bccd5c594908eR338.

I added a couple helper function `highestPriorityThresholds`, which returns the thresholds with highest priority, and `isHigherPriorityThresholds`, which returns an array of the higher priority thresholds.

2022-11-21 20:50 UTC, diehbria approved these changes

2022-11-22 23:04 UTC, merged